# Generated by Django 5.1 on 2024-08-30 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Watch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("price", models.IntegerField()),
                ("year", models.IntegerField()),
                ("condition", models.TextField(blank=True, null=True)),
                ("contents", models.TextField(blank=True, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="images/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("our_pick", models.BooleanField(default=False)),
                ("timeless", models.BooleanField(default=False)),
                ("rare_and_iconic", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WatchSecondaryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_images",
                        to="website.watch",
                    ),
                ),
            ],
        ),
    ]
