# Generated by Django 5.1 on 2024-09-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="date_added_to_our_pick",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="watch",
            name="date_added_to_rare_and_iconic",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="watch",
            name="date_added_to_timeless",
            field=models.DateField(blank=True, null=True),
        ),
    ]
