# Generated by Django 5.1 on 2024-08-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="watch",
            old_name="Name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="watch",
            name="image",
            field=models.ImageField(upload_to="website/static/website/watches/"),
        ),
    ]
