# Generated by Django 5.1 on 2024-08-14 20:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_rename_name_watch_name_alter_watch_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="watch",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
