# Generated by Django 5.1 on 2024-09-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_watch_date_added_to_our_pick_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watch",
            name="date_added_to_our_pick",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="date_added_to_rare_and_iconic",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="watch",
            name="date_added_to_timeless",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
