# Generated by Django 5.1 on 2024-08-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_watch_timestamp_alter_watch_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchSecondaryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "watch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secondary_images",
                        to="website.watch",
                    ),
                ),
            ],
        ),
    ]
