# Generated by Django 5.1 on 2024-08-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_watchsecondaryimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="watch",
            name="our_pick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="watch",
            name="rare_and_iconic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="watch",
            name="timeless",
            field=models.BooleanField(default=False),
        ),
    ]
