"""
Django settings for delta project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Prod stuff
import os
from dotenv import load_dotenv
load_dotenv('./website/keys.env')

SECRET_KEY = os.getenv('SECRET_KEY')
SECURE_HSTS_SECONDS = 31536000

DEBUG = True if os.getenv('DEBUG') == "True" else False if os.getenv('DEBUG') == "False" else None
SECURE_SSL_REDIRECT = False if os.getenv('SECURE_SSL_REDIRECT') == "False" else True if os.getenv('SECURE_SSL_REDIRECT') == "True" else None
SESSION_COOKIE_SECURE = False if os.getenv('SESSION_COOKIE_SECURE') == "False" else True if os.getenv('SESSION_COOKIE_SECURE') == "True" else None
CSRF_COOKIE_SECURE = False if os.getenv('CSRF_COOKIE_SECURE') == "False" else True if os.getenv('CSRF_COOKIE_SECURE') == "True" else None
SECURE_HSTS_INCLUDE_SUBDOMAINS = False if os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS') == "False" else True if os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS') == "True" else None
SECURE_HSTS_PRELOAD = False if os.getenv('SECURE_HSTS_PRELOAD') == "False" else True if os.getenv('SECURE_HSTS_PRELOAD') == "True" else None

if DEBUG == None:
    DEBUG = True if os.getenv('DEBUG2') == "True" else False
    SECURE_SSL_REDIRECT = False if os.getenv('SECURE_SSL_REDIRECT2') == "False" else True
    SESSION_COOKIE_SECURE = False if os.getenv('SESSION_COOKIE_SECURE2') == "False" else True
    CSRF_COOKIE_SECURE = False if os.getenv('CSRF_COOKIE_SECURE2') == "False" else True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False if os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS2') == "False" else True
    SECURE_HSTS_PRELOAD = False if os.getenv('SECURE_HSTS_PRELOAD2') == "False" else True

ALLOWED_HOSTS = ["deltatimepiecesllc.com", "www.deltatimepiecesllc.com", "144.202.17.114", "127.0.0.1", "delta-timepieces-e966006c84b4.herokuapp.com"]


# Application definition

INSTALLED_APPS = [
    "website",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = "delta.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "website.utils.context_processors.cart_processor"
            ],
        },
    },
]

WSGI_APPLICATION = "delta.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'